# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180626_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': '作者夫人', 'verbose_name_plural': '作者夫人'},
        ),
        migrations.AddField(
            model_name='author',
            name='pulisher',
            field=models.ManyToManyField(to='index.Publisher'),
        ),
    ]
