# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20180626_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='pulisher1',
            new_name='pulisher',
        ),
    ]
