# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'ordering': ['desc'], 'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='goodstype',
        ),
    ]
